# Generated by Django 5.1.4 on 2025-04-03 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_student_address_alter_student_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
    ]
